[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # Default exclusions
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
  
  # Custom exclusions for package directories
  | terraform/.*/package
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip_glob = ["*/package/*", "venv/*", ".git/*", "build/*", "dist/*"]