version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Cypress and dependencies...
      - npm init -y
      - npm install cypress --save-dev
      - npm install @cypress/webpack-preprocessor --save-dev
      
  pre_build:
    commands:
      - echo Downloading test files from S3...
      - aws s3 sync s3://${S3_BUCKET}/cypress-tests cypress/e2e/
      - echo Setting up Cypress configuration...
      - |
        cat > cypress.config.js << EOF
        const { defineConfig } = require('cypress')
        
        module.exports = defineConfig({
          e2e: {
            baseUrl: process.env.BASE_URL || 'http://localhost:3000',
            supportFile: false,
            video: true,
            screenshotOnRunFailure: true,
            viewportWidth: 1280,
            viewportHeight: 720,
            defaultCommandTimeout: 10000,
            requestTimeout: 10000,
            responseTimeout: 10000,
          },
        })
        EOF
        
  build:
    commands:
      - echo Running Cypress tests...
      - npx cypress run --spec "cypress/e2e/**/*.cy.js"
      
  post_build:
    commands:
      - echo Cypress tests completed
      - |
        if [ -d "cypress/videos" ]; then
          echo Uploading test videos to S3...
          aws s3 sync cypress/videos s3://${S3_BUCKET}/test-results/videos/
        fi
      - |
        if [ -d "cypress/screenshots" ]; then
          echo Uploading test screenshots to S3...
          aws s3 sync cypress/screenshots s3://${S3_BUCKET}/test-results/screenshots/
        fi

artifacts:
  files:
    - cypress/videos/**/*
    - cypress/screenshots/**/*
  name: cypress-test-results
  
reports:
  cypress_results:
    files:
      - 'cypress/results/*.xml'
    file-format: 'JUNITXML'
